name=(input("Enter name of employee : "))
basic=float(input("Enter Basic Salary : "))
da=float(basic*0.25)
hra=float(basic*0.15)
ta=float(basic*0.075)
net=float(basic+da+hra+ta)
print("===========================")
print(" NAME OF EMPLOYEE : ",name)
print(" BASIC SALARY : ",basic)
print(" NET SALARY PAY : ",net)
print("===========================")